# Generated by Django 2.2.1 on 2020-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=128, unique=True, verbose_name='音乐名字')),
                ('music_address', models.CharField(max_length=255, unique=True, verbose_name='音乐地址')),
                ('music_img_address', models.CharField(max_length=128, verbose_name='专辑图片')),
            ],
            options={
                'verbose_name': '音乐数据',
                'db_table': 'MusicAddress',
            },
        ),
    ]
