# Generated by Django 2.2.1 on 2020-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdata',
            name='music_address',
            field=models.CharField(max_length=128, unique=True, verbose_name='音乐地址'),
        ),
        migrations.AlterModelTable(
            name='musicdata',
            table='MusicData',
        ),
    ]
